skills/myapp/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('skills.myapp.views',
    url(r'^list/$', 'list', name='list'),
)

skills/skills/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

import views
import wxapi
import tbapi

urlpatterns = patterns('',
		#management
		url(r'^admin/$', include(admin.site.urls)),
		url(r'^index/$', views.dispatch),
		url(r'^search/$', views.search),
		url(r'^login/$', views.login),

		url(r'^manage/$', views.manage),
		url(r'^manage/tab/(?P<tab>\w+)/$', views.manage),
		#url(r'^manage/tab/(?P<tab>\w+)/(?P<action>\w+)/$', views.manage),
		url(r'^activity/(?P<optype>\w+)/$', views.activity_op),
		#url(r'^businessman/(?P<optype>\w+)/$', views.businessman_op),

		#url(r'^activity/(?P<optype>\w+)/', views.activity_op),
		url(r'^register/normal/$', views.register),

		url(r'^register/business/end/$', views.register_business_end),
		url(r'^register/business/$', views.register_business,name='list'),

		url(r'^ajax*$', views.ajax_process),
		#management END.

		#wxapi
		#activities/special-offers?area=xxx&age=x&page=x&page_size=x 
		url(r'^activities/special-offers$', wxapi.activities_special_offers),
		#activities/preview?area=xxx&age=x&page=x&page_size=x 
		url(r'^activities/preview$', wxapi.activities_preview),
		#activities/details/{uuid} 
		url(r'^activities/details$', wxapi.activities_details),
		#get-auth-code?phone=138xxx 
		url(r'^get-auth-code$', wxapi.get_authcode),
		#/auth 
		url(r'^wxauth$', wxapi.wxauth_idencode),
		#activities/sign
		url(r'^activities/sign$', wxapi.activities_sign),
		#activities/my
		url(r'^activities/my$', wxapi.activities_my),
		#acitivities/reset?openid={openid}
		url(r'^activities/reset$', wxapi.activities_reset),
		#feedback
		#url(r'^wxfeedback$', wxapi.wxfeedback,
		#activities/get-areas
		url(r'^api/admin/get-areas$', wxapi.activities_getareas),
		url(r'^activities/get-agesel$', wxapi.activities_getagesel),
		url(r'^activities/get_profile$', wxapi.activities_getprofile),
		url(r'^activities/get_qrcode$', wxapi.activities_getqrcode),
		#activities/mycollections
		url(r'^activities/mycollections$', wxapi.activities_mycollections),
		#acitivities/reset_collection?openid={openid}
		url(r'^activities/reset_collection$', wxapi.activities_reset_collection),
		url(r'^activities/collection/get_status$', wxapi.activities_getcollectionstatus),
		#activities/collect
		url(r'^activities/collect$', wxapi.activities_collect),
		url(r'^activities/get_signup_status$', wxapi.activities_getsignupstatus),
		url(r'^activities/unpay/list$', wxapi.activities_myunpay_list),
		#
		#wxapi END.
		
		#tbapi.
		#0818.
		url(r'^api/admin/activity-sign-user$', tbapi.get_activity_sign_user),
		url(r'^api/admin/activity/publish$', tbapi.activity_publish),
		url(r'^api/admin/current-activities$', tbapi.get_publish_activities),
		url(r'^api/admin/unpublish-activities$', tbapi.get_unpublish_activities),
		url(r'^api/admin/login$', tbapi.tbauth),
		url(r'^api/admin/signup-first-step$', tbapi.signup_first_step),
		url(r'^api/admin/signup-second-step$', tbapi.signup_second_step),

		url(r'^api/admin/uploadtoken/get$', tbapi.get_uploadtoken),
		url(r'^api/admin/get-userinfo$', tbapi.get_userinfo),
		url(r'^api/admin/manager/statistic$', tbapi.get_manager_statistic),
		url(r'^api/admin/export-activity-users$', tbapi.get_export_activity_users),
		url(r'^api/admin/replace-qr$', tbapi.replace_qr),
		#0822.
		url(r'^api/admin/activities/preference/add$', tbapi.add_preference),
		url(r'^api/admin/activities/preference/list$', tbapi.get_preferencelist),
		#0823
		url(r'^api/admin/business/authorize$', tbapi.business_authorize),
		url(r'^api/admin/account/set$', tbapi.account_set),
		url(r'^api/admin/get-cities$', wxapi.activities_getcities),
		#0824
		url(r'^api/superadmin/businessman/list$', tbapi.businessman_list),
		url(r'^api/superadmin/signup/list$', tbapi.signup_list),
		#0830
		url(r'^api/admin/get-acttypes$', tbapi.get_acttypes),
		url(r'^api/admin/activities/add$', tbapi.add_activity),
		#url(r'^api/admin/replace-qr$', tbapi.replace_qr),
		#tbapi END.
		url(r'^$', wxapi.default_process),
		url(r'^get_access_token$', wxapi.get_access_token),
		url(r'^wx_test$', wxapi.save_pos_wx),
		url(r'^get_6sid$', wxapi.get_openid),
		url(r'^get_js_signature$', wxapi.get_js_signature),
		#0926
		url(r'^wx/acttypes/list$', wxapi.get_wx_acttypes),
		#0928
		url(r'^activities/hot/list$', wxapi.get_hot_activities),
		url(r'^wx/nearbyareas/list$', wxapi.get_nearbyareas),
		url(r'^wxpay/$', wxapi.wxpay),
		url(r'^testwxpay$', wxapi.testwxpay),
		url(r'^get_wx_payinfo$', wxapi.get_wx_payinfo),
		#lxp
		#url(r'^lxpbuild$', wxapi.lxpbuild),
		#url(r'^lxpback$', wxapi.lxpback),
)

skills/myapp/models.py
# -*- coding: utf-8 -*-
from django.db import models

class Document(models.Model):
		docfile = models.FileField(upload_to='documents/%Y/%m/%d')
		
		#using for permission. 
		class Meta:
				permissions = (
								("role_admin", "admin do"),
								("role_businessman", "businessman do"),
								("role_visitor", "visitor do"),
						)
		

skills/myapp/forms.py
# -*- coding: utf-8 -*-
from django import forms

class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )
    #https://docs.djangoproject.com/en/1.9/ref/forms/fields/

skills/myapp/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from skills.myapp.models import Document
from skills.myapp.forms import DocumentForm

def list(request):
    # Handle file upload
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            newdoc = Document(docfile = request.FILES['docfile'])
            newdoc.save()

            # Redirect to the document list after POST
            return HttpResponseRedirect(reverse('skills.myapp.views.list'))
    else:
        form = DocumentForm() # A empty, unbound form

    # Load documents for the list page
    documents = Document.objects.all()

    # Render list page with the documents and the form
    return render_to_response(
        'myapp/list.html',
        {'documents': documents, 'form': form},
        context_instance=RequestContext(request)
    )

skills/myapp/templates/myapp/list.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Minimal Django File Upload Example</title>	
	</head>

	<body>
		<!-- List of uploaded documents -->
		{% if documents %}
			<ul>
			{% for document in documents %}
				<li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a></li>
			{% endfor %}
			</ul>
		{% else %}
			<p>No documents.</p>
		{% endif %}

		<!-- Upload form. Note enctype attribute! -->
		<form action="{% url "list" %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<p>{{ form.non_field_errors }}</p>
			<p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>
			<p>
				{{ form.docfile.errors }}
				{{ form.docfile }}
			</p>
			<p><input type="submit" value="Upload" /></p>
		</form>
		
	</body>

</html> 

skills/templates/register.html
<!DOCTYPE html>
<!-- saved from url=(0041)http://v3.bootcss.com/examples/offcanvas/ -->
<html lang="zh-CN">
  
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v3.bootcss.com/favicon.ico">
    <title>Off Canvas Template for Bootstrap</title>
    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/static/css/offcanvas_main.css" rel="stylesheet">
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/ie8-responsive-file-warning.js"></script>
    <![endif]-->
    <script src="/static/js/ie-emulation-modes-warning.js"></script>
    <style>body { padding-top:50px; } h1 { color: black; } div { margin-bottom:2px } .align-right {text-align:right;margin-top:5px} .form-group { margin-bottom:2px }  #content{ width:100%; min-height:600px; background:white; padding-top:20px; color:black; } .register{ padding: 20px; font-weight:700; border:black solid 1px; -moz-border-radius: 10px; /* Gecko browsers */ -webkit-border-radius: 10px; /* Webkit browsers */ border-radius:10px; /* W3C syntax */ }
</style>
    <script language="javascript">
    function CheckAndSubmit() // 验证表单数据有效性
      {
        if (username.value == "") {
          window.alert('请输入用户名!');
          return false;
        }
        if (username.value.length < 3) {
          window.alert('用户名长度必须大于3!');
          return false;
        }
        if (password.value == "") {
          alert('请输入密码!');
          return false;
        }
        if (password.value.length < 6) {
          alert('密码长度必须大于6!');
          return false;
        }
        if (password.value != chkpwd.value) {
          alert('确认密码与密码不一致!');
          return false;
        }/*
        if (email.value == "") {
          alert('请输入Email!');
          return false;
        }
        if (email.value.indexOf("@") == -1) {
          alert('请输入有效的email地址!');
          return false;
        }*/
        var regBox = {
          regEmail: /^([a-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})$/,
          //邮箱
          regName: /^[a-z0-9_-]{3,16}$/,
          //用户名
          regMobile: /^0?1[3|4|5|8][0-9]\d{8}$/,
          //手机
          regTel: /^0[\d]{2,3}-[\d]{7,8}$/
        }
        var mflag = regBox.regMobile.test(phone.value);
        if (phone.value == "") {
          alert('请输入手机号码!');
          return false;
        }
        /*if (!mflag) {
          alert('请输入有效的手机号码!');
          return false;
        }*/
        if (document.getElementsByName("regtyperd")[0].checked) {
          regtype.value = "business";
        }
        else if (document.getElementsByName("regtyperd")[1].checked) {
          regtype.value = "normal";
        }
        /*if (document.send.authcode.value == "") {
          alert('请输入验证码!');
          return false;
        }*/
        postform.submit();
        return true;
      }

function submit_userinfo(){
$.ajax({
    url: '/ajax?name=register_userinfo',
    data:{  
        selRollBack : selRollBack,  
        selOperatorsCode : selOperatorsCode,  
        pass2 : pass2  
    },  
    dataType : 'json',
    cache: false,
    success: function(data) {
        alert('Load was performed.'+data.ajax_resp);
        self.location='/register_business';
    },
    error : function() {  
        // view("异常！");  
         alert("异常！");  
    }  
})};

window.onload = function() { 
{% if obj.einfo.error %}
alert("{{obj.einfo.error}}"); 
{% endif %}
};


</script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
  
  <body>
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="http://v3.bootcss.com/examples/offcanvas/#">六艺</a></div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active">
              <a href="http://v3.bootcss.com/examples/offcanvas/#">主页</a></li>
            <!--<li>
              <a href="http://v3.bootcss.com/examples/offcanvas/#about">About</a></li>
            <li>
              <a href="http://v3.bootcss.com/examples/offcanvas/#contact">Contact</a></li>-->
          </ul>
        </div>
        <!-- /.nav-collapse --></div>
      <!-- /.container --></nav>
    <!-- /.navbar -->
    <div id="content">
      <div class="container">
        <form action="/register/normal/" method="post" enctype="multipart/form-data" id="postform" >
          <input type="hidden" name="actype_normal"/>
          <div class="row">
            <h1 class="col-md-6 col-md-offset-3 col-xs-10 col-xs-offset-1 page_title ">注册</h1></div>
          <div class="col-md-6 col-md-offset-3 col-xs-10 col-xs-offset-1 register">
            <div class="form-group">
              <label for="username" class="col-sm-3 control-label align-right">用户名：</label>
              <div class="col-sm-8">
                <div class="input-group">
                  <input type="text" class="form-control" name="username" id="username" placeholder="请输入用户名">
                  <div class="input-group-addon">
                    <span class="glyphicon glyphicon-user"></span>
                  </div>
                </div>
              </div>
            </div>
            <div class="form-group">
              <label for="password" class="col-sm-3 control-label align-right">密码：</label>
              <div class="col-sm-8">
                <div class="input-group">
                  <input type="password" class="form-control" name="password" id="password" placeholder="请输入密码（六位以上）">
                  <div class="input-group-addon">
                    <span class="glyphicon glyphicon-lock"></span>
                  </div>
                </div>
              </div>
            </div>
            <div class="form-group">
              <label for="chkpwd" class="col-sm-3 control-label align-right">确认密码：</label>
              <div class="col-sm-8">
                <div class="input-group">
                  <input type="password" class="form-control" name="chkpwd" id="chkpwd" placeholder="请确认密码">
                  <div class="input-group-addon">
                    <span class="glyphicon glyphicon-exclamation-sign"></span>
                  </div>
                </div>
              </div>
            </div>
            <!-- <div class="form-group">
            <label for="email" class="col-sm-3 control-label  align-right">邮箱：</label>
            <div class="col-sm-8">
            <div class="input-group">
            <input type="text" class="form-control" name="email" placeholder="请输入有效邮箱">
            <div class="input-group-addon">
            <span class="glyphicon glyphicon-envelope"></span></div></div>
            </div>
            </div>
            -->
            <div class="form-group">
              <label for="headportrait" class="col-sm-3 control-label align-right">头像：</label>
              <div class="col-sm-8">
                <div class="input-group">
                {% csrf_token %}
                <p><!--
                    {{ form.docfile.errors }}
                    {{ form.docfile }}-->
                </p>
                <input id="id_docfile" name="docfile" type="file" />
                </div>
              </div>
            </div>
            <div class="form-group">
              <label for="phone" class="col-sm-3 control-label align-right">手机号码：</label>
              <div class="col-sm-8">
                <div class="input-group">
                  <input type="text" class="form-control" name="phone" id="phone" placeholder="请输入有效电话">
                  <div class="input-group-addon">
                    <span class="glyphicon glyphicon-headphones"></span>
                  </div>
                </div>
              </div>
            </div>
            <div class="form-group">
              <label for="phone" class="col-sm-3 control-label"></label>
              <div class="col-sm-8">
                <div class="input-group">
                  <div class="input-group">
                    <label><input name="regtyperd" type="radio" value="business" checked/>商户 </label>&nbsp&nbsp
                    <label><input name="regtyperd" type="radio" value="normal" />普通访客 </label>&nbsp
                  </div>
                </div>
              </div>
            </div>

            <!--<div class="form-group">
              <label for="authcode" class="col-sm-3 control-label">验证码：</label>
              <div class="col-sm-5">
                <div class="input-group">
                  <input type="text" class="form-control" name="authcode" placeholder="请输入验证码">
                  <div class="input-group-addon">
                    <span class="glyphicon glyphicon-ok"></span>
                  </div>
                </div>
              </div>
              <label for="authcode_img" class="control-label col-sm-1" style="padding-top: 0px;">
                <a class="btn btn-default" href="javascript:void(0)" onclick="document.getElementById('captcha_img').src='authcode.php?r'+Math.random()" title="换一个">
                  <img id="captcha_img" src="" alt="验证码"></a>
              </label>
            </div>-->
            <div class="row">
              <div class="col-md-3 col-md-offset-3 col-xs-12">
                <button class="btn btn-default btn-block">
                  <b>&nbsp;&nbsp;清空</b>
                  <span class="glyphicon glyphicon-remove"></span>
                </button>
              </div>
              <div class="col-md-3 col-xs-12">
                <input type="button" value="&nbsp;&nbsp;提交&nbsp;&nbsp;" onclick="CheckAndSubmit()" class="btn btn-primary btn-block">
                  
                </input>&nbsp&nbsp&nbsp&nbsp
              </div>
            </div>
              <div style="text-align:right">
                <a href="/login">用现有账号登陆</a>
              </div>
          </div>
          <input type="hidden" name="regtype" id="regtype" />
        </form>
        <br/>
        <!-- 注册表单结束 --></div>
      <div class="container">
        <hr>
        <footer>
          <p>© Company 2014</p>
        </footer>
      </div>
    </div>
    <!--/.container-->
    <!-- Bootstrap core JavaScript==================================================- ->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/static/js/ie10-viewport-bug-workaround.js"></script>
    <script src="/static/js/offcanvas.js"></script>
  </body>

</html>

skills/templates/register_business_end.html
<!DOCTYPE html>
<!-- saved from url=(0041)http://v3.bootcss.com/examples/offcanvas/ -->
<html lang="zh-CN">
  
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v3.bootcss.com/favicon.ico">
    <title>Off Canvas Template for Bootstrap</title>
    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/static/css/offcanvas_main.css" rel="stylesheet">
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/ie8-responsive-file-warning.js"></script>
    <![endif]-->
    <script src="/static/js/ie-emulation-modes-warning.js"></script>
<style>body { padding-top:50px; } h1 { color: black; } #content{ width:100%; min-height:600px; background:white url(footer.png); padding-top:20px; color:black; } .register{ padding: 20px; font-weight:700; border:black solid 1px; -moz-border-radius: 10px; /* Gecko browsers */ -webkit-border-radius: 10px; /* Webkit browsers */ border-radius:10px; /* W3C syntax */ }
</style>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]--></head>
  
  <body>
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="http://v3.bootcss.com/examples/offcanvas/#">6skills</a></div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active">
              <a href="http://v3.bootcss.com/examples/offcanvas/#">Home</a></li>
            <li>
              <a href="http://v3.bootcss.com/examples/offcanvas/#about">About</a></li>
            <li>
              <a href="http://v3.bootcss.com/examples/offcanvas/#contact">Contact</a></li>
          </ul>
        </div>
        <!-- /.nav-collapse --></div>
      <!-- /.container --></nav>
    <!-- /.navbar -->
    <div class="container">
      <div class="row">
        <div class="col-sm-8 blog-main">
<div id="content">
      <div class="container">
            <h1 class="col-md-6 col-md-offset-2 col-xs-10 col-xs-offset-2 page_title ">等待审核</h1><br/>

	<div class="col-md-6 col-md-offset-1 col-xs-10 col-xs-offset-1">
	<hr/>
        <h4>您提交的信息已经收到，正在审核中，一个工作日内将会收到审核结果通知，请您耐心等待.</h4><br/>
		  


            

          </div>
        <br/>
        <!-- 注册表单结束 --></div>

    </div>		
        </div>
        <!-- /.blog-main -->
        <div class="col-sm-3">
          <div class="sidebar-module sidebar-module-inset">
            <h4>合作流程</h4>
            <p>第1步：<em>商家提交公司信息</em></p>
            <p>第1步：<em>商家提交公司信息</em></p>
            <p>第1步：<em>商家提交公司信息</em></p>
            <hr/>
            <h4>合作须知</h4>
            <p>1、什么是六艺开放平台？
 
依托于优质的用户资源，与高质量的供应商合作，为消费者提供全方位的、优质的、便捷的亲子活动服务。
 
2、六艺开放平台覆盖哪些服务品类？
 
六艺开放平台致力于满足用户对亲子活动的需求场景，目前优先覆盖以下品类：本地亲子活动、亲子出游、兴趣培养、早教等。
 
3、对服务商有什么要求？需要哪些资质？
 
六艺开放平台仅选择服务体验优质的供应商进行合作，对于服务体验不达标的供应商将不予入驻。
 
重点考核服务商的以下服务体验：
 
－至少覆盖1个城市，可服务一定量级的用户
－服务礼仪、服务流程有统一的标准规范
－服务所需的工具、耗材均为正品
－服务质量在行业内领先
－售后服务体系完善等
服务商资质需符合国家规定，合作前需提供以下证件（所有证件需在有效期内）：
 
－企业营业执照副本复印件
－税务登记证复印件
－组织机构代码证复印件
－银行开户许可证复印件
－法人代表人身份证正反面复印件
－行业所需其他特殊资质
5、与六艺合作需要收费吗？
 
六艺暂不向服务商收取任何佣金和手续费。
 
6、与六艺合作需要保证金吗？
 
六艺暂不向服务商收取保证金。
 
7、提交信息后多长时间会给予回复？
 
收到您提交的合作信息后，会在1个工作日内进行审核。如果符合合作要求，我们在3个工作日内联系您洽谈合作；如果您的服务项目不符合合作要求，则暂时对您的项目没有合作意向，请您谅解，同时也会短信和邮件通知您，建议您提交信息时相关联系方式尽量保证齐全。</p>
          </div>
<!--
          <div class="sidebar-module">
            <h4>Archives</h4>
            <ol class="list-unstyled">
              <li>
                <a href="#">March 2014</a></li>
              <li>
                <a href="#">February 2014</a></li>
              <li>
                <a href="#">January 2014</a></li>
              <li>
                <a href="#">December 2013</a></li>
              <li>
                <a href="#">November 2013</a></li>
              <li>
                <a href="#">October 2013</a></li>
              <li>
                <a href="#">September 2013</a></li>
              <li>
                <a href="#">August 2013</a></li>
              <li>
                <a href="#">July 2013</a></li>
              <li>
                <a href="#">June 2013</a></li>
              <li>
                <a href="#">May 2013</a></li>
              <li>
                <a href="#">April 2013</a></li>
            </ol>
          </div>
-->
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li>
                <a href="#">GitHub</a></li>
              <li>
                <a href="#">Twitter</a></li>
              <li>
                <a href="#">Facebook</a></li>
            </ol>
          </div>
        </div>
        <!-- /.blog-sidebar --></div>
      <!--/row-->
      <hr>
      <footer>
        <p>© Company 2014</p>
      </footer>
    </div>
    <!--/.container-->
    <!-- Bootstrap core JavaScript==================================================- ->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/static/js/ie10-viewport-bug-workaround.js"></script>
    <script src="/static/js/offcanvas.js"></script>
  </body>

</html>

skills/templates/signin.html
<!DOCTYPE html>
<!-- saved from url=(0038)http://v3.bootcss.com/examples/signin/ -->
<html lang="zh-CN"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v3.bootcss.com/favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/signin.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/static/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
<script language="javascript">
window.onload = function() { 
{% if obj.einfo.error %}
alert("{{obj.einfo.error}}"); 
{% endif %}
};
</script>


  </head>

  <body>

    <div class="container">

      <form class="form-signin" action="/login/" method="post">
        <h2 class="form-signin-heading">Please sign in</h2>
        <label for="inputName" class="sr-only">Username</label>
        <input name="log_username" class="form-control" placeholder="Username" required="" autofocus="">
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" name="log_password" class="form-control" placeholder="Password" required="">
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/static/js/ie10-viewport-bug-workaround.js"></script>
  

</body></html>